2018-01-02 14:15:17,469 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:39]
2018-01-02 14:15:28,515 ERROR: Exception on /edit_profile [POST] [in /home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jb/git_local/microblog/app/routes.py", line 87, in edit_profile
    db.session.commit()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 937, in commit
    self.transaction.commit()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2237, in flush
    self._flush(objects)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2363, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2327, in _flush
    flush_context.execute()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username [SQL: 'UPDATE user SET username=?, about_me=? WHERE user.id = ?'] [parameters: ('susan', 'Now let me tell you about John.', 2)] (Background on this error at: http://sqlalche.me/e/gkpj)
2018-01-02 18:42:24,660 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:42]
2018-01-02 19:40:40,601 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:42]
2018-01-02 19:40:50,702 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:42]
2018-01-02 19:46:49,261 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:42]
2018-01-02 21:02:34,310 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:42]
2018-01-02 21:12:26,046 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:42]
2018-01-03 14:14:44,965 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:42]
2018-01-03 14:19:36,045 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-03 19:21:07,726 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-03 19:28:25,099 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-03 19:35:13,712 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-03 19:51:28,538 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-03 19:55:12,703 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-03 20:16:52,527 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-03 20:39:03,296 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-03 20:51:37,698 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:01:05,033 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:01:34,574 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:03:13,103 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:30:39,982 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:31:59,467 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:32:28,615 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:38:13,132 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:41:41,966 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:42:23,529 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:43:06,963 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:45:30,013 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:45:36,664 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:45:41,498 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
2018-01-05 21:45:47,076 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:41]
